id: P004624
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16787
  title: ཚ་བ་རིང་མདའ་རྫོང་།
  author: ''
  volumes:
    efd623af87e74b4daf3140e59a7a55b1:
      image_group_id: I1KG16896
      title: ''
      volume_number: 1
      total_pages: 518
      base_file: v001.txt
